version: '3.8'

services:
  bot:
    container_name: fl-bot
    build: .
  db:
    container_name: db
    ports:
      - '5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    image: postgres:15.2